In [1]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = ['pecanproject_pecan',	'esa-philab_opensartoolkit', 'stolllab_easyspin',	'mariohsouto_proxsdp.jl',
'qiskit_qiskit-experiments',	'ericproffitt_topicmodelsvb.jl',	'vcityteam_ud-reproducibility',
'hbctraining_scrna-seq_online',	'smileipic_smilei',	'geofranzi_geoportal']
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1             project
0  00002128a7de94e5e9d1df1e9fcacff8183bcdad  pecanproject_pecan

In [ ]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  1%|          | 63/7162 [01:08<2:08:27,  1.09s/it]

Got Errors {'0440008edc4bf973a152ccdd8c6fc46415f2bb17': 'Key 0440008edc4bf973a152ccdd8c6fc46415f2bb17 not found in /da5_fast/All.sha1c/commit_4.tch'}

  1%|          | 88/7162 [01:36<2:07:38,  1.08s/it]

Got Errors {'05f1f47f3e5139c750ae05689ec91ac4d441ca98': 'Key 05f1f47f3e5139c750ae05689ec91ac4d441ca98 not found in /da5_fast/All.sha1c/commit_5.tch'}

  2%|▏         | 123/7162 [02:14<2:09:00,  1.10s/it]

Got Errors {'0847ae93057bf45ce0abad0cd93f0cb7a1d74ecb': 'Key 0847ae93057bf45ce0abad0cd93f0cb7a1d74ecb not found in /da5_fast/All.sha1c/commit_8.tch'}

  2%|▏         | 126/7162 [02:17<2:07:26,  1.09s/it]

Got Errors {'086786d6110cf7686e31b165a7a6a29dbdc8a471': 'Key 086786d6110cf7686e31b165a7a6a29dbdc8a471 not found in /da5_fast/All.sha1c/commit_8.tch'}

  3%|▎         | 248/7162 [04:30<2:04:26,  1.08s/it]

Got Errors {'107ec6348924af3c5e4434ea0e1814ac5aa5daf2': 'Key 107ec6348924af3c5e4434ea0e1814ac5aa5daf2 not found in /da5_fast/All.sha1c/commit_16.tch'}

  4%|▎         | 255/7162 [04:38<2:03:42,  1.07s/it]

Got Errors {'10fa1c8a94d2486e6104cb71cc27a81c6d784c4b': 'Key 10fa1c8a94d2486e6104cb71cc27a81c6d784c4b not found in /da5_fast/All.sha1c/commit_16.tch'}

  5%|▍         | 328/7162 [05:57<2:05:17,  1.10s/it]

Got Errors {'15faff9fab67fa171a0e464176647126a9fb228f': 'Key 15faff9fab67fa171a0e464176647126a9fb228f not found in /da5_fast/All.sha1c/commit_21.tch'}

  6%|▌         | 440/7162 [07:58<2:01:40,  1.09s/it]

Got Errors {'1d404bde9b9f181b8eb956c63b9e6a20a1fd258a': 'Key 1d404bde9b9f181b8eb956c63b9e6a20a1fd258a not found in /da5_fast/All.sha1c/commit_29.tch'}

  7%|▋         | 477/7162 [08:38<2:00:44,  1.08s/it]

Got Errors {'1fb70541b0365bc4b09c6397355ab8380e7af98c': 'Key 1fb70541b0365bc4b09c6397355ab8380e7af98c not found in /da5_fast/All.sha1c/commit_31.tch'}

  7%|▋         | 487/7162 [08:49<2:00:35,  1.08s/it]

Got Errors {'2062bff2577719b97a36adee4773c01b8df84717': 'Key 2062bff2577719b97a36adee4773c01b8df84717 not found in /da5_fast/All.sha1c/commit_32.tch'}

  7%|▋         | 504/7162 [09:08<2:00:08,  1.08s/it]

Got Errors {'21761f3ddf1361c941095589aad37fefe99b1773': 'Key 21761f3ddf1361c941095589aad37fefe99b1773 not found in /da5_fast/All.sha1c/commit_33.tch'}

  7%|▋         | 517/7162 [09:22<1:59:42,  1.08s/it]

Got Errors {'2266bfc0fd23ce005a01e677951c214cf3434166': 'Key 2266bfc0fd23ce005a01e677951c214cf3434166 not found in /da5_fast/All.sha1c/commit_34.tch'}

  7%|▋         | 536/7162 [09:42<1:59:05,  1.08s/it]

Got Errors {'239f0781bba2c3c6c14d7525ba1d7626461e3ed5': 'Key 239f0781bba2c3c6c14d7525ba1d7626461e3ed5 not found in /da5_fast/All.sha1c/commit_35.tch'}

  8%|▊         | 562/7162 [10:10<2:00:28,  1.10s/it]

Got Errors {'2558d4709b5ed9dedbb650a588054d6c636f512a': 'Key 2558d4709b5ed9dedbb650a588054d6c636f512a not found in /da5_fast/All.sha1c/commit_37.tch'}

  9%|▉         | 627/7162 [11:21<1:57:57,  1.08s/it]

Got Errors {'29861c583e2e627cf91e13dfe1414d511e3103e0': 'Key 29861c583e2e627cf91e13dfe1414d511e3103e0 not found in /da5_fast/All.sha1c/commit_41.tch'}

 10%|▉         | 697/7162 [12:37<1:56:23,  1.08s/it]

Got Errors {'2e11158eff2651edbe9d7b86dbecb2f4607a62ad': 'Key 2e11158eff2651edbe9d7b86dbecb2f4607a62ad not found in /da5_fast/All.sha1c/commit_46.tch'}

 15%|█▍        | 1064/7162 [19:14<1:49:19,  1.08s/it]

Got Errors {'45f353b8c5ad64032063cc65b26ad950b856a3fe': 'Key 45f353b8c5ad64032063cc65b26ad950b856a3fe not found in /da5_fast/All.sha1c/commit_69.tch'}

 16%|█▌        | 1131/7162 [20:27<1:48:13,  1.08s/it]

Got Errors {'4a752a0c930cfc5f57797201b8e53e52e15b21d2': 'Key 4a752a0c930cfc5f57797201b8e53e52e15b21d2 not found in /da5_fast/All.sha1c/commit_74.tch'}

 17%|█▋        | 1226/7162 [22:11<1:50:12,  1.11s/it]

Got Errors {'509d1cc475a8ac6c9e309e4f91c8903064159b9d': 'Key 509d1cc475a8ac6c9e309e4f91c8903064159b9d not found in /da5_fast/All.sha1c/commit_80.tch'}

 18%|█▊        | 1261/7162 [22:49<1:46:31,  1.08s/it]

Got Errors {'53034d472dfee3d00f68f49e3c0a3b7344f42b6d': 'Key 53034d472dfee3d00f68f49e3c0a3b7344f42b6d not found in /da5_fast/All.sha1c/commit_83.tch'}

 18%|█▊        | 1265/7162 [22:53<1:46:32,  1.08s/it]

Got Errors {'5349c791cf3d4ddc2a23b86c3b24d442161b8165': 'Key 5349c791cf3d4ddc2a23b86c3b24d442161b8165 not found in /da5_fast/All.sha1c/commit_83.tch'}

 19%|█▉        | 1396/7162 [25:16<1:44:29,  1.09s/it]

Got Errors {'5ba5a17386aeb0452279b44716bc4140544aea8d': 'Key 5ba5a17386aeb0452279b44716bc4140544aea8d not found in /da5_fast/All.sha1c/commit_91.tch'}

 21%|██        | 1491/7162 [26:59<1:42:20,  1.08s/it]

Got Errors {'61da69993c3bd1e2c8c25e1a4928c4295f10ab9e': 'Key 61da69993c3bd1e2c8c25e1a4928c4295f10ab9e not found in /da5_fast/All.sha1c/commit_97.tch'}

 23%|██▎       | 1653/7162 [29:55<1:38:59,  1.08s/it]

Got Errors {'6c990008b8ecde53b8176959936b9019f547255e': 'Key 6c990008b8ecde53b8176959936b9019f547255e not found in /da5_fast/All.sha1c/commit_108.tch'}

 23%|██▎       | 1669/7162 [30:13<1:40:02,  1.09s/it]

Got Errors {'6da44204f5cbb51a5a9990a5e45a0bee1bc1c26b': 'Key 6da44204f5cbb51a5a9990a5e45a0bee1bc1c26b not found in /da5_fast/All.sha1c/commit_109.tch'}

 24%|██▍       | 1708/7162 [30:55<1:38:27,  1.08s/it]

Got Errors {'70124aca715877df4bc202907f05fb2ed09ef962': 'Key 70124aca715877df4bc202907f05fb2ed09ef962 not found in /da5_fast/All.sha1c/commit_112.tch'}

 24%|██▍       | 1716/7162 [31:04<1:37:43,  1.08s/it]

Got Errors {'70903f02d4bd553c5496aa5e6a20339fb9999b03': 'Key 70903f02d4bd553c5496aa5e6a20339fb9999b03 not found in /da5_fast/All.sha1c/commit_112.tch'}

 25%|██▌       | 1821/7162 [32:58<1:36:14,  1.08s/it]

Got Errors {'777b02a34ad7fc0b028850b6f3bff44d8b7b9ac9': 'Key 777b02a34ad7fc0b028850b6f3bff44d8b7b9ac9 not found in /da5_fast/All.sha1c/commit_119.tch'}

 27%|██▋       | 1906/7162 [34:31<1:37:50,  1.12s/it]

Got Errors {'7d3f7df2b451da9901ebd9d8b164020b75cc2ecf': 'Key 7d3f7df2b451da9901ebd9d8b164020b75cc2ecf not found in /da5_fast/All.sha1c/commit_125.tch'}

 27%|██▋       | 1967/7162 [35:38<1:37:28,  1.13s/it]

Got Errors {'81246a48d48b963bed812792923204d9bba3e38c': 'Key 81246a48d48b963bed812792923204d9bba3e38c not found in /da5_fast/All.sha1c/commit_1.tch'}

 32%|███▏      | 2261/7162 [40:59<1:28:32,  1.08s/it]

Got Errors {'945809dc8301ad65f364ea0dd6959c82703ad513': 'Key 945809dc8301ad65f364ea0dd6959c82703ad513 not found in /da5_fast/All.sha1c/commit_20.tch'}

 34%|███▍      | 2462/7162 [44:36<1:24:45,  1.08s/it]

Got Errors {'a1e877a01ff582ebde515ac56c0c4b1c6dc754cd': 'Key a1e877a01ff582ebde515ac56c0c4b1c6dc754cd not found in /da5_fast/All.sha1c/commit_33.tch'}

 37%|███▋      | 2682/7162 [48:36<1:20:58,  1.08s/it]

Got Errors {'b08e85f4233d805a6ba122db1c8ae05f9c088c0b': 'Key b08e85f4233d805a6ba122db1c8ae05f9c088c0b not found in /da5_fast/All.sha1c/commit_48.tch'}

 39%|███▊      | 2768/7162 [50:09<1:19:20,  1.08s/it]

Got Errors {'b6221e0659ca8c01113cf330679ac4a662194eea': 'Key b6221e0659ca8c01113cf330679ac4a662194eea not found in /da5_fast/All.sha1c/commit_54.tch'}

 39%|███▉      | 2778/7162 [50:20<1:19:11,  1.08s/it]

Got Errors {'b6c443c3ea21ed5326190dfb314370f130886465': 'Key b6c443c3ea21ed5326190dfb314370f130886465 not found in /da5_fast/All.sha1c/commit_54.tch'}

 40%|███▉      | 2836/7162 [51:23<1:18:15,  1.09s/it]

Got Errors {'baa29ddf160683276ba7d2f67c45cdfb09a76708': 'Key baa29ddf160683276ba7d2f67c45cdfb09a76708 not found in /da5_fast/All.sha1c/commit_58.tch'}

 41%|████      | 2915/7162 [52:49<1:16:54,  1.09s/it]

Got Errors {'bf6f67299b56a22fb06ba4a5791c6cb94c4e3ef9': 'Key bf6f67299b56a22fb06ba4a5791c6cb94c4e3ef9 not found in /da5_fast/All.sha1c/commit_63.tch'}

 43%|████▎     | 3088/7162 [55:58<1:13:13,  1.08s/it]

Got Errors {'ca8006168c177f2a3ea79a625c0ba55763db4c4a': 'Key ca8006168c177f2a3ea79a625c0ba55763db4c4a not found in /da5_fast/All.sha1c/commit_74.tch'}

 44%|████▎     | 3125/7162 [56:38<1:12:47,  1.08s/it]

Got Errors {'ccee663e1c489319625d38c59470739ff036bad9': 'Key ccee663e1c489319625d38c59470739ff036bad9 not found in /da5_fast/All.sha1c/commit_76.tch'}

 44%|████▍     | 3187/7162 [57:46<1:11:51,  1.08s/it]

Got Errors {'d11901298ba7609d7d731eb1f5e392b14d054657': 'Key d11901298ba7609d7d731eb1f5e392b14d054657 not found in /da5_fast/All.sha1c/commit_81.tch'}

 45%|████▌     | 3234/7162 [58:37<1:10:39,  1.08s/it]

Got Errors {'d4498ebaba5e957f9815344a2a80cd08a58862e0': 'Key d4498ebaba5e957f9815344a2a80cd08a58862e0 not found in /da5_fast/All.sha1c/commit_84.tch'}

 46%|████▌     | 3275/7162 [59:21<1:09:56,  1.08s/it]

Got Errors {'d7028781af012566a0d79114e50c91fc9b089d67': 'Key d7028781af012566a0d79114e50c91fc9b089d67 not found in /da5_fast/All.sha1c/commit_87.tch'}

 46%|████▌     | 3299/7162 [59:47<1:09:47,  1.08s/it]

Got Errors {'d897529d6f7de1c4ddce4d9cbcecbfe0726fc1d2': 'Key d897529d6f7de1c4ddce4d9cbcecbfe0726fc1d2 not found in /da5_fast/All.sha1c/commit_88.tch'}

 48%|████▊     | 3441/7162 [1:02:21<1:06:55,  1.08s/it]

Got Errors {'e1cb5276f7e4acdce9b725a2dc4d0f17071fd8c4': 'Key e1cb5276f7e4acdce9b725a2dc4d0f17071fd8c4 not found in /da5_fast/All.sha1c/commit_97.tch'}

 49%|████▊     | 3477/7162 [1:03:00<1:05:58,  1.07s/it]

Got Errors {'e4493398d2bc01ec84b12f42a9b2f6dc719eab97': 'Key e4493398d2bc01ec84b12f42a9b2f6dc719eab97 not found in /da5_fast/All.sha1c/commit_100.tch'}

 49%|████▉     | 3523/7162 [1:03:49<1:05:21,  1.08s/it]

Got Errors {'e71afc8b296bd4b2d8ae57374aed67654ad16f38': 'Key e71afc8b296bd4b2d8ae57374aed67654ad16f38 not found in /da5_fast/All.sha1c/commit_103.tch'}

 49%|████▉     | 3529/7162 [1:03:56<1:05:17,  1.08s/it]

Got Errors {'e7657a89408d375e70707bf0ecefbc161cfefe79': 'Key e7657a89408d375e70707bf0ecefbc161cfefe79 not found in /da5_fast/All.sha1c/commit_103.tch'}

 49%|████▉     | 3531/7162 [1:03:58<1:07:28,  1.12s/it]

Got Errors {'e78f34e0e76700687d4e26dc90a9d5acb6d8f140': 'Key e78f34e0e76700687d4e26dc90a9d5acb6d8f140 not found in /da5_fast/All.sha1c/commit_103.tch'}

 50%|████▉     | 3562/7162 [1:04:31<1:04:51,  1.08s/it]

Got Errors {'e99b6f8400fceea42a9f99ad144dfe2e78b05c1b': 'Key e99b6f8400fceea42a9f99ad144dfe2e78b05c1b not found in /da5_fast/All.sha1c/commit_105.tch'}

 50%|█████     | 3585/7162 [1:04:56<1:04:33,  1.08s/it]

Got Errors {'eaf43481b0cc861e022d91c09144af2ce5d2f6e6': 'Key eaf43481b0cc861e022d91c09144af2ce5d2f6e6 not found in /da5_fast/All.sha1c/commit_106.tch'}

 50%|█████     | 3606/7162 [1:05:19<1:04:16,  1.08s/it]

Got Errors {'ec5efd61e53885962932d8121bec2113e924c825': 'Key ec5efd61e53885962932d8121bec2113e924c825 not found in /da5_fast/All.sha1c/commit_108.tch'}

 52%|█████▏    | 3698/7162 [1:06:59<1:02:25,  1.08s/it]

Got Errors {'f2467366c442a548b685c0761ec44b37f66994df': 'Key f2467366c442a548b685c0761ec44b37f66994df not found in /da5_fast/All.sha1c/commit_114.tch'}

 52%|█████▏    | 3740/7162 [1:07:44<1:02:01,  1.09s/it]

Got Errors {'f5017808cf1691865a83ced7d6fb8bd9872f1d30': 'Key f5017808cf1691865a83ced7d6fb8bd9872f1d30 not found in /da5_fast/All.sha1c/commit_117.tch'}

 53%|█████▎    | 3824/7162 [1:09:16<1:00:10,  1.08s/it]

Got Errors {'face400e26f05348a432dfe76924e88d54d60839': 'Key face400e26f05348a432dfe76924e88d54d60839 not found in /da5_fast/All.sha1c/commit_122.tch'}

 54%|█████▎    | 3848/7162 [1:09:41<59:37,  1.08s/it]

Got Errors {'fc6891135164c418d3d5a639fbe6f32b669060ba': 'Key fc6891135164c418d3d5a639fbe6f32b669060ba not found in /da5_fast/All.sha1c/commit_124.tch'}

 59%|█████▉    | 4239/7162 [1:16:49<53:21,  1.10s/it]

Got Errors {'3f97d6b9ddd2b47d37d350708cfcb547180c997d': 'Key 3f97d6b9ddd2b47d37d350708cfcb547180c997d not found in /da5_fast/All.sha1c/commit_63.tch'}

 59%|█████▉    | 4249/7162 [1:17:00<54:07,  1.11s/it]

Got Errors {'64d3772e84e45cd63338db166a2a3ccb488f9663': 'Key 64d3772e84e45cd63338db166a2a3ccb488f9663 not found in /da5_fast/All.sha1c/commit_100.tch'}

 59%|█████▉    | 4253/7162 [1:17:05<53:09,  1.10s/it]

Got Errors {'6f1262cd5081fa7e9adfef4afeb459b0b1a3b516': 'Key 6f1262cd5081fa7e9adfef4afeb459b0b1a3b516 not found in /da5_fast/All.sha1c/commit_111.tch'}

 60%|█████▉    | 4265/7162 [1:17:18<52:44,  1.09s/it]

Got Errors {'989a274490c961f391387ba649fca66145eaa2c8': 'Key 989a274490c961f391387ba649fca66145eaa2c8 not found in /da5_fast/All.sha1c/commit_24.tch'}

 60%|█████▉    | 4266/7162 [1:17:19<52:42,  1.09s/it]

Got Errors {'9920ed734762fb80ba4ec82395faf37b94808f1a': 'Key 9920ed734762fb80ba4ec82395faf37b94808f1a not found in /da5_fast/All.sha1c/commit_25.tch'}

 60%|█████▉    | 4285/7162 [1:17:40<51:54,  1.08s/it]

Got Errors {'cfd780aa34b27b1e1ddd161de5e1d0cb26296c04': 'Key cfd780aa34b27b1e1ddd161de5e1d0cb26296c04 not found in /da5_fast/All.sha1c/commit_79.tch'}

 60%|█████▉    | 4292/7162 [1:17:47<51:52,  1.08s/it]

Got Errors {'df99f4480c899090941df22bb0097e9b9c5f04b1': 'Key df99f4480c899090941df22bb0097e9b9c5f04b1 not found in /da5_fast/All.sha1c/commit_95.tch'}

 60%|██████    | 4302/7162 [1:17:58<52:15,  1.10s/it]

Got Errors {'fdfefe167746a1700c79cba3d4fb915bf2ac31ea': 'Key fdfefe167746a1700c79cba3d4fb915bf2ac31ea not found in /da5_fast/All.sha1c/commit_125.tch'}

 76%|███████▋  | 5474/7162 [1:39:16<30:29,  1.08s/it]

Got Errors {'0b97040dac7300a111657640cd27382fd1f5c2b2': 'Key 0b97040dac7300a111657640cd27382fd1f5c2b2 not found in /da5_fast/All.sha1c/commit_11.tch'}

 82%|████████▏ | 5889/7162 [1:46:49<22:51,  1.08s/it]

Got Errors {'08da6d3776607b8d3e4121b7602f25b0f57efd77': 'Key 08da6d3776607b8d3e4121b7602f25b0f57efd77 not found in /da5_fast/All.sha1c/commit_8.tch'}

 83%|████████▎ | 5911/7162 [1:47:13<22:36,  1.08s/it]

Got Errors {'0d8b4f18efe0414728c275bb3f7bfdd6df3f2e61': 'Key 0d8b4f18efe0414728c275bb3f7bfdd6df3f2e61 not found in /da5_fast/All.sha1c/commit_13.tch'}

 83%|████████▎ | 5920/7162 [1:47:23<22:28,  1.09s/it]

Got Errors {'0f1b28ce1110e3456b7b8201f74f10dc99c2d910': 'Key 0f1b28ce1110e3456b7b8201f74f10dc99c2d910 not found in /da5_fast/All.sha1c/commit_15.tch'}

 83%|████████▎ | 5927/7162 [1:47:31<22:23,  1.09s/it]

Got Errors {'10c20413e7ac47f590560bb4964db6d5169a1516': 'Key 10c20413e7ac47f590560bb4964db6d5169a1516 not found in /da5_fast/All.sha1c/commit_16.tch'}

 83%|████████▎ | 5941/7162 [1:47:46<22:00,  1.08s/it]

Got Errors {'13dac56c3baf7264781c2e28ec7d162d1c6d102b': 'Key 13dac56c3baf7264781c2e28ec7d162d1c6d102b not found in /da5_fast/All.sha1c/commit_19.tch'}

 83%|████████▎ | 5952/7162 [1:47:58<21:48,  1.08s/it]

Got Errors {'160037d43d76feb8a9ce6042746d4d36dbb085de': 'Key 160037d43d76feb8a9ce6042746d4d36dbb085de not found in /da5_fast/All.sha1c/commit_22.tch'}

 83%|████████▎ | 5959/7162 [1:48:05<21:41,  1.08s/it]

Got Errors {'172f61b15ce4ad9fbd8aed5317afefb638d9e2e7': 'Key 172f61b15ce4ad9fbd8aed5317afefb638d9e2e7 not found in /da5_fast/All.sha1c/commit_23.tch'}

 84%|████████▍ | 6018/7162 [1:49:10<20:39,  1.08s/it]

Got Errors {'22ffc62e859410560b26672a80eb6f75b0e14bf7': 'Key 22ffc62e859410560b26672a80eb6f75b0e14bf7 not found in /da5_fast/All.sha1c/commit_34.tch'}

 85%|████████▌ | 6095/7162 [1:50:33<19:15,  1.08s/it]

Got Errors {'336c63a0a85f10627f69bc1b9561120bcb7d484a': 'Key 336c63a0a85f10627f69bc1b9561120bcb7d484a not found in /da5_fast/All.sha1c/commit_51.tch'}

 86%|████████▌ | 6164/7162 [1:51:48<18:06,  1.09s/it]

Got Errors {'41a791768429cb6eecaf9244c262e4a93b6c263e': 'Key 41a791768429cb6eecaf9244c262e4a93b6c263e not found in /da5_fast/All.sha1c/commit_65.tch'}

 86%|████████▋ | 6194/7162 [1:52:21<17:26,  1.08s/it]

Got Errors {'47f29c01dffa7004827758ca544245784db450e5': 'Key 47f29c01dffa7004827758ca544245784db450e5 not found in /da5_fast/All.sha1c/commit_71.tch'}

 88%|████████▊ | 6291/7162 [1:54:07<15:58,  1.10s/it]

Got Errors {'5d7aa3eb5bf5bf09a6e3a50e09760efdcead5e36': 'Key 5d7aa3eb5bf5bf09a6e3a50e09760efdcead5e36 not found in /da5_fast/All.sha1c/commit_93.tch'}

 91%|█████████ | 6495/7162 [1:57:48<11:59,  1.08s/it]

Got Errors {'8a69b845ccb834fb74335880fce0d6735fd332ad': 'Key 8a69b845ccb834fb74335880fce0d6735fd332ad not found in /da5_fast/All.sha1c/commit_10.tch'}

 92%|█████████▏| 6603/7162 [1:59:45<10:05,  1.08s/it]

Got Errors {'a0a8b1f0a2f57ed46f1cd708020777ff8d93b2c1': 'Key a0a8b1f0a2f57ed46f1cd708020777ff8d93b2c1 not found in /da5_fast/All.sha1c/commit_32.tch'}

 94%|█████████▍| 6717/7162 [2:01:49<08:02,  1.08s/it]

Got Errors {'b8afad66fc6679cd06bdc2cd024c8c4352aa4311': 'Key b8afad66fc6679cd06bdc2cd024c8c4352aa4311 not found in /da5_fast/All.sha1c/commit_56.tch'}

 94%|█████████▍| 6763/7162 [2:02:40<07:31,  1.13s/it]

Got Errors {'c1df0683c3be5c577c490a19d4f785c6daec309f': 'Key c1df0683c3be5c577c490a19d4f785c6daec309f not found in /da5_fast/All.sha1c/commit_65.tch'}

 97%|█████████▋| 6927/7162 [2:05:38<04:21,  1.11s/it]

Got Errors {'e5323ceaa72f7162d4125c7f6f23989c0d090db3': 'Key e5323ceaa72f7162d4125c7f6f23989c0d090db3 not found in /da5_fast/All.sha1c/commit_101.tch'}

100%|██████████| 7162/7162 [2:09:54<00:00,  1.09s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,00002128a7de94e5e9d1df1e9fcacff8183bcdad,c468e14dfbd6f5393d078c2c0439405264813e4c,[d6138d49eb85eb2cf86b8567b6824756578acab0],Betsy Cowdery <emcowdery@gmail.com>,1479233072,-0500,Betsy Cowdery <emcowdery@gmail.com>,1479233072,-0500,Fixing external function call\n,00002128a7de94e5e9d1df1e9fcacff8183bcdad,pecanproject_pecan
1,0000896d56a7024d7019a01bc671771176ed3800,909e2fac51199214661e9922d0949dfa76fdc22a,[ea9862bd3ee531328a34397ee5714d4018a242d6],Betsy Cowdery <emcowdery@gmail.com>,1478089294,-0400,Betsy Cowdery <emcowdery@gmail.com>,1478089307,-0400,Adding optional argument var.ids so that only ...,0000896d56a7024d7019a01bc671771176ed3800,pecanproject_pecan

In [3]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '00002128a7de94e5e9d1df1e9fcacff8183bcdad', 'tree': 'c468e14dfbd6f5393d078c2c0439405264813e4c', 'parent': ['d6138d49eb85eb2cf86b8567b6824756578acab0'], 'author': 'Betsy Cowdery <emcowdery@gmail.com>', 'author_time': 1479233072, 'author_tz': '-0500', 'committer': 'Betsy Cowdery <emcowdery@gmail.com>', 'committer_time': 1479233072, 'committer_tz': '-0500', 'message': 'Fixing external function call\n'}

In [52]:
dfinf = df_commit_data[['project', 'commit', 'author', 'author_time', 'message']].copy()
dfinf.rename(columns={'author_time': 'time'}, inplace=True)

# Sanitize all whitespace, newlines, and semicolons
dfinf['message'] = (
    dfinf['message']
    .astype(str)
    .str.replace(r'[\r\n]+', ' ', regex=True)
    .str.replace(';', ',')
    .str.strip()
)

In [53]:
print("Shape:", dfinf.shape)

Shape: (71531, 5)

In [63]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
#dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
#for k in commit_data:
#  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
#  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [54]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,pecanproject_pecan,00002128a7de94e5e9d1df1e9fcacff8183bcdad,Betsy Cowdery <emcowdery@gmail.com>,1479233072,Fixing external function call

In [64]:
dfinf.shape

(71531, 5)

In [62]:
#mode a means append, so you have all your projects in the same file
yournetid='jbronyah'
#dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)
dfinf.to_csv(yournetid + '_project_summary.csv', index=False, sep=';', mode='w', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

In [61]:
import pandas as pd

# Compute World of Code (WoC) metrics per project from df_commit_data
woc_stats = df_commit_data.groupby('project').agg(
    commits=('commit', 'count'),
    authors=('author', 'nunique'),
    From=('author_time', 'min'),
    To=('author_time', 'max')
).reset_index()

woc_stats.rename(columns={
    'commits': '#commits',
    'authors': '#authors'
}, inplace=True)

# GitHub repository metrics
gh_metrics = pd.DataFrame([
    {
        'project': 'pecanproject_pecan',
        '#stars': 246,
        '#forks': 321,
        'LastGHCommitDate': '2026/09/25'
    },
    {
        'project': 'esa-philab_opensartoolkit',
        '#stars': 248,
        '#forks': 60,
        'LastGHCommitDate': '2026/02/04'
    },
    {
        'project': 'stolllab_easyspin',
        '#stars': 66,
        '#forks': 29,
        'LastGHCommitDate': '2026/09/28'
    },
    {
        'project': 'mariohsouto_proxsdp.jl',
        '#stars': 97,
        '#forks': 13,
        'LastGHCommitDate': '2025/05/25'
    },
    {
        'project': 'qiskit_qiskit-experiments',
        '#stars': 197,
        '#forks': 139,
        'LastGHCommitDate': '2026/09/09'
    },
    {
        'project': 'ericproffitt_topicmodelsvb.jl',
        '#stars': 84,
        '#forks': 9,
        'LastGHCommitDate': '2025/02/09'
    },
    {
        'project': 'vcityteam_ud-reproducibility',
        '#stars': 2,
        '#forks': 2,
        'LastGHCommitDate': '2024/11/21'
    },
    {
        'project': 'hbctraining_scrna-seq_online',
        '#stars': 672,
        '#forks': 209,
        'LastGHCommitDate': '2026/08/20'
    },
    {
        'project': 'smileipic_smilei',
        '#stars': 449,
        '#forks': 157,
        'LastGHCommitDate': '2026/09/14'
    },
    {
        'project': 'geofranzi_geoportal',
        '#stars': 0,
        '#forks': 0,
        'LastGHCommitDate': '2025/05/12'
    },
])

# Merge WoC statistics with GitHub data
df_project_stats = woc_stats.merge(gh_metrics, on='project', how='left')

# 4. Display the table in the notebook
display(df_project_stats)

# Export
#df_project_stats.to_csv('jbronyah_project_stats.csv', sep=';', index=False)

,project,#commits,#authors,From,To,#stars,#forks,LastGHCommitDate
0,ericproffitt_topicmodelsvb.jl,1542,11,1466824003,1741617121,84,9,2025/02/09
1,esa-philab_opensartoolkit,637,31,1542903465,1758635026,248,60,2026/02/04
2,geofranzi_geoportal,1169,14,1467280640,1756391053,0,0,2025/05/12
3,hbctraining_scrna-seq_online,1619,16,1514765279,1744731382,672,209,2026/08/20
4,mariohsouto_proxsdp.jl,831,20,1515506544,1748191005,97,13,2025/05/25
5,pecanproject_pecan,38951,454,1283468974,1776459632,246,321,2026/09/25
6,qiskit_qiskit-experiments,11635,145,1614191172,1762367916,197,139,2026/09/09
7,smileipic_smilei,11931,212,1364546318,1761655373,449,157,2026/09/14
8,stolllab_easyspin,2542,41,1318928290,1759430732,66,29,2026/09/28
9,vcityteam_ud-reproducibility,674,26,1576158853,1732201063,2,2,2024/11/21